namespace CNewsProject.StaticTempData;

public static class ExchangeRateData
{
    public static int SEK { get; set; } = 1;
    public static double AED { get; set; }
    public static double AFN { get; set; }
    public static double ALL { get; set; }
    public static double AMD { get; set; }
    public static double ANG { get; set; }
    public static double AOA { get; set; }
    public static double ARS { get; set; }
    public static double AUD { get; set; }
    public static double AWG { get; set; }
    public static double AZN { get; set; }
    public static double BAM { get; set; }
    public static double BBD { get; set; }
    public static double BDT { get; set; }
    public static double BGN { get; set; }
    public static double BHD { get; set; }
    public static double BIF { get; set; }
    public static double BMD { get; set; }
    public static double BND { get; set; }
    public static double BOB { get; set; }
    public static double BRL { get; set; }
    public static double BSD { get; set; }
    public static double BTN { get; set; }
    public static double BWP { get; set; }
    public static double BYN { get; set; }
    public static double BZD { get; set; }
    public static double CAD { get; set; }
    public static double CDF { get; set; }
    public static double CHF { get; set; }
    public static double CLP { get; set; }
    public static double CNY { get; set; }
    public static double COP { get; set; }
    public static double CRC { get; set; }
    public static double CUP { get; set; }
    public static double CVE { get; set; }
    public static double CZK { get; set; }
    public static double DJF { get; set; }
    public static double DKK { get; set; }
    public static double DOP { get; set; }
    public static double DZD { get; set; }
    public static double EGP { get; set; }
    public static double ERN { get; set; }
    public static double ETB { get; set; }
    public static double EUR { get; set; }
    public static double FJD { get; set; }
    public static double FKP { get; set; }
    public static double FOK { get; set; }
    public static double GBP { get; set; }
    public static double GEL { get; set; }
    public static double GGP { get; set; }
    public static double GHS { get; set; }
    public static double GIP { get; set; }
    public static double GMD { get; set; }
    public static double GNF { get; set; }
    public static double GTQ { get; set; }
    public static double GYD { get; set; }
    public static double HKD { get; set; }
    public static double HNL { get; set; }
    public static double HRK { get; set; }
    public static double HTG { get; set; }
    public static double HUF { get; set; }
    public static double IDR { get; set; }
    public static double ILS { get; set; }
    public static double IMP { get; set; }
    public static double INR { get; set; }
    public static double IQD { get; set; }
    public static double IRR { get; set; }
    public static double ISK { get; set; }
    public static double JEP { get; set; }
    public static double JMD { get; set; }
    public static double JOD { get; set; }
    public static double JPY { get; set; }
    public static double KES { get; set; }
    public static double KGS { get; set; }
    public static double KHR { get; set; }
    public static double KID { get; set; }
    public static double KMF { get; set; }
    public static double KRW { get; set; }
    public static double KWD { get; set; }
    public static double KYD { get; set; }
    public static double KZT { get; set; }
    public static double LAK { get; set; }
    public static double LBP { get; set; }
    public static double LKR { get; set; }
    public static double LRD { get; set; }
    public static double LSL { get; set; }
    public static double LYD { get; set; }
    public static double MAD { get; set; }
    public static double MDL { get; set; }
    public static double MGA { get; set; }
    public static double MKD { get; set; }
    public static double MMK { get; set; }
    public static double MNT { get; set; }
    public static double MOP { get; set; }
    public static double MRU { get; set; }
    public static double MUR { get; set; }
    public static double MVR { get; set; }
    public static double MWK { get; set; }
    public static double MXN { get; set; }
    public static double MYR { get; set; }
    public static double MZN { get; set; }
    public static double NAD { get; set; }
    public static double NGN { get; set; }
    public static double NIO { get; set; }
    public static double NOK { get; set; }
    public static double NPR { get; set; }
    public static double NZD { get; set; }
    public static double OMR { get; set; }
    public static double PAB { get; set; }
    public static double PEN { get; set; }
    public static double PGK { get; set; }
    public static double PHP { get; set; }
    public static double PKR { get; set; }
    public static double PLN { get; set; }
    public static double PYG { get; set; }
    public static double QAR { get; set; }
    public static double RON { get; set; }
    public static double RSD { get; set; }
    public static double RUB { get; set; }
    public static double RWF { get; set; }
    public static double SAR { get; set; }
    public static double SBD { get; set; }
    public static double SCR { get; set; }
    public static double SDG { get; set; }
    public static double SGD { get; set; }
    public static double SHP { get; set; }
    public static double SLE { get; set; }
    public static double SLL { get; set; }
    public static double SOS { get; set; }
    public static double SRD { get; set; }
    public static double SSP { get; set; }
    public static double STN { get; set; }
    public static double SYP { get; set; }
    public static double SZL { get; set; }
    public static double THB { get; set; }
    public static double TJS { get; set; }
    public static double TMT { get; set; }
    public static double TND { get; set; }
    public static double TOP { get; set; }
    public static double TRY { get; set; }
    public static double TTD { get; set; }
    public static double TVD { get; set; }
    public static double TWD { get; set; }
    public static double TZS { get; set; }
    public static double UAH { get; set; }
    public static double UGX { get; set; }
    public static double USD { get; set; }
    public static double UYU { get; set; }
    public static double UZS { get; set; }
    public static double VES { get; set; }
    public static double VND { get; set; }
    public static double VUV { get; set; }
    public static double WST { get; set; }
    public static double XAF { get; set; }
    public static double XCD { get; set; }
    public static double XDR { get; set; }
    public static double XOF { get; set; }
    public static double XPF { get; set; }
    public static double YER { get; set; }
    public static double ZAR { get; set; }
    public static double ZMW { get; set; }
    public static double ZWL { get; set; }
}
